import { Employee, Group } from "types/domain";

const employeeMockResponse = [
  {
    id: 1,
    pdmId: 1,
    firstName: "Goober",
    lastName: "Spavon",
    internationalName: "Goober Spavon",
    title: "Structural Analysis Engineer",
    email: "gspavon0@example.com",
    managementGroup: "Accounting",
    companyCode: "IJL RU-AH",
    businessUnit: "Road Logistics",
    costCenter: "HBC92CO",
    companyPhone: "865-477-5428",
    companyMobilePhone: "465-300-9830",
    gender: "Female",
    nationality: "Kazakhstan",
    office: {
      countryiso3: "AFG",
      city: "Aqsū",
      street: "28574 Melrose Hill",
      postalCode: "7005-676",
      country: "Afghanistan",
    },
    birthDate: "05/07/1989",
    startDate: "11/05/1994",
    endDate: null,
    dateOfLeave: null,
    careMember: true,
  },
  {
    id: 2,
    pdmId: 2,
    firstName: "Sean",
    lastName: "Sapwell",
    internationalName: "Sean Sapwell",
    title: "Chemical Engineer",
    email: "ssapwell1@nbcnews.com",
    managementGroup: "Accounting",
    companyCode: "FWN KE-HK",
    businessUnit: "Air Logistics",
    costCenter: "EOW42SM",
    companyPhone: "378-466-6027",
    companyMobilePhone: "694-884-8124",
    gender: "Male",
    nationality: "China",
    office: {
      countryiso3: "ALB",
      city: "Huangzhan",
      street: "739 Sauthoff Park",
      postalCode: "7005-676",
      country: "Albania",
    },
    birthDate: "10/08/1999",
    startDate: "08/06/2001",
    endDate: null,
    dateOfLeave: null,
    careMember: true,
  },
  {
    id: 3,
    pdmId: 3,
    firstName: "Boot",
    lastName: "Whithalgh",
    internationalName: "Boot Whithalgh",
    title: "Senior Financial Analyst",
    email: "bwhithalgh2@wix.com",
    managementGroup: "Research and Development",
    companyCode: "EPX GL-UV",
    businessUnit: "Sea Logistics",
    costCenter: "DFZ22ZX",
    companyPhone: "467-727-9633",
    companyMobilePhone: "126-384-1948",
    gender: "Male",
    nationality: "Iran",
    office: {
      countryiso3: "DZA",
      city: "Sarvābād",
      street: "55273 Summit Avenue",
      postalCode: "7005-676",
      country: "Algeria",
    },
    birthDate: "28/05/1988",
    startDate: "02/04/2010",
    endDate: null,
    dateOfLeave: null,
    careMember: true,
  },
  {
    id: 4,
    pdmId: 4,
    firstName: "Romain",
    lastName: "Otridge",
    internationalName: "Romain Otridge",
    title: "Teacher",
    email: "rotridge3@abc.net.au",
    managementGroup: "Human Resources",
    companyCode: "TQO MQ-GH",
    businessUnit: "Sales",
    costCenter: "GBK82XZ",
    companyPhone: "301-976-5111",
    companyMobilePhone: "585-178-4916",
    gender: "Female",
    nationality: "China",
    office: {
      countryiso3: "ASM",
      city: "Ziyang",
      street: "713 Arrowood Center",
      postalCode: "7005-676",
      country: "American Samoa",
    },
    birthDate: "11/08/1983",
    startDate: "01/02/1993",
    endDate: null,
    dateOfLeave: null,
    careMember: true,
  },
  {
    id: 5,
    pdmId: 5,
    firstName: "Boigie",
    lastName: "Semeradova",
    internationalName: "Boigie Semeradova",
    title: "Staff Accountant III",
    email: "bsemeradova4@accuweather.com",
    managementGroup: "Services",
    companyCode: "ZMN PU-VT",
    businessUnit: "Contract Logistics",
    costCenter: "PBY42LU",
    companyPhone: "187-366-1353",
    companyMobilePhone: "815-128-7157",
    gender: "Male",
    nationality: "China",
    office: {
      countryiso3: "AND",
      city: "Baima",
      street: "7 Nancy Pass",
      postalCode: "7005-676",
      country: "Andorra",
    },
    birthDate: "09/08/1987",
    startDate: "11/02/1992",
    endDate: null,
    dateOfLeave: null,
    careMember: true,
  },
] as Employee[];

const groupMockResponse = {
  data: [
    {
      id: 1,
      name: "Brainy Buddies",
      description: "Nothing can be achieved without having fun.",
      active: true,
      members: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    },
    {
      id: 2,
      name: "Dynamite Dealers",
      description: "Can't beat them at negotiation or Monopoly..",
      active: true,
      members: [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    },
    {
      id: 3,
      name: "Unfrozen Caveman",
      description:
        "If you need extreme solution they are there for you. Might be rude from time to time",
      active: true,
      members: [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
    },
    {
      id: 4,
      name: "Mind Serenade",
      description: "They always comes with new ideas, out from the box",
      active: true,
      members: [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
    },
    {
      id: 5,
      name: "Clan Optimism",
      description: "Watch the bright side of everything",
      active: true,
      members: [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
    },
  ] as Group[],
};

const mockData = {
  get: jest.fn(url => {
    if (url.includes("/employee")) {
      return Promise.resolve(employeeMockResponse);
    }
    if (url.includes("/group")) {
      return Promise.resolve(groupMockResponse);
    }
    return null;
  }),
  create: () => mockData,
  defaults: {
    adapter: {},
  },
};

export default mockData;
